name = "MzvHoffmanAlgebra"
uuid = "c963f718-e780-4a39-abe6-39cbaa8cd120"
authors = ["いーな <kankitsumikan0424@gmail.com>", "Y.K.495 <yuttarikanata@gmail.com>"]
version = "1.2.0-DEV"

[compat]
julia = "1.12.1"
